// Autogenerated from Pigeon (v22.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class UserDetails;

@interface UserDetails : NSObject
+ (instancetype)makeWithEmail:(nullable NSString *)email
    name:(nullable NSString *)name;
@property(nonatomic, copy, nullable) NSString * email;
@property(nonatomic, copy, nullable) NSString * name;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetPigeonCodec(void);

@protocol UserApi
/// @return `nil` only when `error != nil`.
- (nullable UserDetails *)getUserDetailsWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)saveUserDetailsDetails:(UserDetails *)details error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpUserApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserApi> *_Nullable api);

extern void SetUpUserApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UserApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
