// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1o4LT5TiEMlXqrTVfGvr2myJQ75NIBzE',
    appId: '1:1036562420737:web:96098123390ef6f489dc00',
    messagingSenderId: '1036562420737',
    projectId: 'finance-6a910',
    authDomain: 'finance-6a910.firebaseapp.com',
    storageBucket: 'finance-6a910.appspot.com',
    measurementId: 'G-4V7M1LX7G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfXJWcTqpMnoO5cshG3CdWPBekxBqAWTw',
    appId: '1:1036562420737:android:4fc1796a1d46938289dc00',
    messagingSenderId: '1036562420737',
    projectId: 'finance-6a910',
    storageBucket: 'finance-6a910.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnhX1Loo59wyqZotbFGadKeZbZ1g8LeNk',
    appId: '1:1036562420737:ios:6089845c70434a6189dc00',
    messagingSenderId: '1036562420737',
    projectId: 'finance-6a910',
    storageBucket: 'finance-6a910.appspot.com',
    iosBundleId: 'com.example.oldPeople',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnhX1Loo59wyqZotbFGadKeZbZ1g8LeNk',
    appId: '1:1036562420737:ios:6089845c70434a6189dc00',
    messagingSenderId: '1036562420737',
    projectId: 'finance-6a910',
    storageBucket: 'finance-6a910.appspot.com',
    iosBundleId: 'com.example.oldPeople',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1o4LT5TiEMlXqrTVfGvr2myJQ75NIBzE',
    appId: '1:1036562420737:web:a6f551a0cd69331e89dc00',
    messagingSenderId: '1036562420737',
    projectId: 'finance-6a910',
    authDomain: 'finance-6a910.firebaseapp.com',
    storageBucket: 'finance-6a910.appspot.com',
    measurementId: 'G-LLHSZ1BQEQ',
  );
}
